# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['*']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/': ~
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        #Â Important since allow_origin contains '*'
        origin_regex: false
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth', 'Origin', 'Content-Type', 'Accept']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'PATCH', 'OPTIONS']
            max_age: 3600
            # This may not be needed ?
            forced_allow_origin_value: '*'
