fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_registration_register:
    path: /api/register
    controller: App\Controller\RegistrationController::registerAction
fos_user_security_login:
    path: /api/login
    controller: App\Controller\SecurityController:loginAction